import type { CallingConvention, CpuArchitecture } from "../types";
import { SHARED_ASM_EXTENSIONS } from "../mn1613/arch";

/** TMS9995 呼び出し規約（ワークスペース / BL） */
export const TMS9995_CALLING_CONVENTION: CallingConvention = {
  argRegisters: ["R1", "R2"],
  returnRegister: "R1",
  calleeSavedNote:
    "BL は戻りアドレスを R11 に保存する。R13–R15 は BLWP / 割り込みコンテキスト用。",
  summaryMarkdown: [
    "**TMS9995 呼び出し規約（慣用）**",
    "",
    "| 役割 | レジスタ |",
    "|------|---------|",
    "| 第1引数 | `R1`（慣用） |",
    "| 第2引数 | `R2` |",
    "| 戻り値 | `R1` |",
    "| BL 戻り | `R11` |",
    "| BLWP 退避 | `R13` WP / `R14` PC / `R15` ST |",
    "",
    "`BL @label` で呼び出し、`RT`（`B *R11`）または `B *R11` で復帰。",
  ].join("\n"),
};

/** retrocpu_asm 第1弾と揃えた命令セット */
const TMS9995_MNEMONICS = [
  // Format 1
  "SZC",
  "SZCB",
  "S",
  "SB",
  "C",
  "CB",
  "A",
  "AB",
  "MOV",
  "MOVB",
  "SOC",
  "SOCB",
  // Format 2
  "JMP",
  "JLT",
  "JLE",
  "JEQ",
  "JHE",
  "JGT",
  "JNE",
  "JNC",
  "JOC",
  "JNO",
  "JL",
  "JH",
  "JOP",
  // Format 6
  "BLWP",
  "B",
  "CLR",
  "NEG",
  "INV",
  "INC",
  "INCT",
  "DEC",
  "DECT",
  "BL",
  "SWPB",
  "SETO",
  "ABS",
  // Format 8 / 7 / 9995+
  "LI",
  "AI",
  "ANDI",
  "ORI",
  "CI",
  "LWPI",
  "LIMI",
  "STWP",
  "STST",
  "LST",
  "LWP",
  "RTWP",
  "RT",
  "IDLE",
  "RSET",
] as const;

const TMS9995_DIRECTIVES = [
  ".ORG",
  "ORG",
  ".EQU",
  "EQU",
  ".WORD",
  "WORD",
  "DW",
  ".DW",
  ".DS",
  "DS",
  ".BLKW",
  "BLKW",
  ".BLKB",
  "BLKB",
  ".AREA",
  "AREA",
  ".GLOBL",
  ".GLOBAL",
  "GLOBL",
  "GLOBAL",
  ".INCLUDE",
  "INCLUDE",
  ".MACRO",
  "MACRO",
  ".ENDM",
  "ENDM",
  ".END",
  "END",
] as const;

const TMS9995_REGISTERS = [
  "R0",
  "R1",
  "R2",
  "R3",
  "R4",
  "R5",
  "R6",
  "R7",
  "R8",
  "R9",
  "R10",
  "R11",
  "R12",
  "R13",
  "R14",
  "R15",
] as const;

/** TMS9995 アーキテクチャ定義（retrocpu_asm 第1弾相当） */
export const tms9995Architecture: CpuArchitecture = {
  id: "tms9995",
  displayName: "TMS9995",
  extensions: [...SHARED_ASM_EXTENSIONS, "tms9995"],
  languageId: "mn1613asm",
  mnemonics: new Set(TMS9995_MNEMONICS),
  directives: new Set(TMS9995_DIRECTIVES),
  registers: new Set(TMS9995_REGISTERS),
  callMnemonics: new Set(["BL", "BLWP"]),
  labelRefMnemonics: new Set([
    "B",
    "BL",
    "BLWP",
    "JMP",
    "JLT",
    "JLE",
    "JEQ",
    "JHE",
    "JGT",
    "JNE",
    "JNC",
    "JOC",
    "JNO",
    "JL",
    "JH",
    "JOP",
  ]),
  callingConvention: TMS9995_CALLING_CONVENTION,
};
