/**
 * TMS9995 命令ホバー用の短い説明。
 * 根拠: TMS9995_instruction.mdc / retrocpu_asm（sdas 構文）
 */

/** ニーモニック → 1 行説明 */
export const TMS9995_INSN_HELP: Readonly<Record<string, string>> = {
  A: "Format 1: `A src, dst` — dst ← dst + src（ワード）",
  AB: "Format 1: `AB src, dst` — バイト加算",
  AI: "Format 8: `AI Rn, #imm` — Rn ← Rn + 即値",
  S: "Format 1: `S src, dst` — dst ← dst − src",
  SB: "Format 1: `SB src, dst` — バイト減算",
  INC: "Format 6: `INC addr` — 値 ← 値 + 1",
  INCT: "Format 6: `INCT addr` — 値 ← 値 + 2",
  DEC: "Format 6: `DEC addr` — 値 ← 値 − 1",
  DECT: "Format 6: `DECT addr` — 値 ← 値 − 2",
  NEG: "Format 6: `NEG addr` — 符号反転",
  ABS: "Format 6: `ABS addr` — 絶対値",
  INV: "Format 6: `INV addr` — ビット反転",
  MPY: "Format 9: `MPY src, Rn` — 符号なし乗算 → R0:R1",
  MPYS: "Format 6: `MPYS src` — 符号あり乗算 → R0:R1（TMS9995+）",
  DIV: "Format 9: `DIV src, Rn` — 符号なし除算（商 R0、余り R1）",
  DIVS: "Format 6: `DIVS src` — 符号あり除算（TMS9995+）",
  SOC: "Format 1: `SOC src, dst` — dst ← dst OR src",
  SOCB: "Format 1: `SOCB src, dst` — バイト OR",
  SZC: "Format 1: `SZC src, dst` — dst ← dst AND NOT src",
  SZCB: "Format 1: `SZCB src, dst` — バイト AND NOT",
  XOR: "Format 3: `XOR src, Rn` — Rn ← Rn XOR src",
  COC: "Format 3: `COC src, Rn` — 対応ビットが 1 か比較（EQ）",
  CZC: "Format 3: `CZC src, Rn` — 対応ビットが 0 か比較",
  ANDI: "Format 8: `ANDI Rn, #imm` — Rn ← Rn AND 即値",
  ORI: "Format 8: `ORI Rn, #imm` — Rn ← Rn OR 即値",
  CI: "Format 8: `CI Rn, #imm` — Rn と即値を比較",
  C: "Format 1: `C src, dst` — ワード比較（フラグのみ）",
  CB: "Format 1: `CB src, dst` — バイト比較",
  MOV: "Format 1: `MOV src, dst` — dst ← src（ワード）",
  MOVB: "Format 1: `MOVB src, dst` — バイト転送",
  LI: "Format 8: `LI Rn, #imm` — Rn ← 即値",
  CLR: "Format 6: `CLR addr` — 0 を書く",
  SETO: "Format 6: `SETO addr` — FFFFh を書く",
  SWPB: "Format 6: `SWPB addr` — 上下バイト入れ替え",
  B: "Format 6: `B addr` — 無条件分岐。`B (R11)` が復帰",
  BL: "Format 6: `BL addr` — 呼び出し。戻り PC を R11 へ",
  BLWP: "Format 6: `BLWP vector` — WP/PC をベクタからロード",
  X: "Format 6: `X addr` — その番地の命令を実行",
  RTWP: "Format 7: ST/PC/WP ← R15/R14/R13",
  XOP: "Format 9: `XOP src, #n` — n=0–15。ベクタへ BLWP。R11 ← src EA",
  JMP: "Format 2: 無条件相対ジャンプ（次命令から −128..127 ワード）",
  JLT: "Format 2: A>=0 かつ EQ=0 でジャンプ",
  JLE: "Format 2: L>=0 または EQ=1 でジャンプ",
  JEQ: "Format 2: EQ=1 でジャンプ",
  JHE: "Format 2: L>=1 または EQ=1 でジャンプ",
  JGT: "Format 2: A>=1 でジャンプ",
  JNE: "Format 2: EQ=0 でジャンプ",
  JNC: "Format 2: C=0 でジャンプ",
  JOC: "Format 2: C=1 でジャンプ",
  JNO: "Format 2: OV=0 でジャンプ",
  JL: "Format 2: L>=0 かつ EQ=0 でジャンプ（符号なし）",
  JH: "Format 2: L>=1 かつ EQ=0 でジャンプ（符号なし）",
  JOP: "Format 2: OP=1 でジャンプ",
  SRA: "Format 5: `SRA Rn, #count` — 算術右シフト（0 は R0 下位 4bit）",
  SRL: "Format 5: `SRL Rn, #count` — 論理右シフト",
  SLA: "Format 5: `SLA Rn, #count` — 左シフト",
  SRC: "Format 5: `SRC Rn, #count` — 循環シフト",
  LDCR: "Format 4: `LDCR addr, #bits` — CRU から読込（0 と 16 は 16bit）",
  STCR: "Format 4: `STCR addr, #bits` — CRU へ書込（0 と 16 は 16bit）",
  SBO: "Format 2: `SBO #disp` — R12 相対で CRU ビットを 1",
  SBZ: "Format 2: `SBZ #disp` — R12 相対で CRU ビットを 0",
  TB: "Format 2: `TB #disp` — CRU ビットをテスト → EQ",
  LWPI: "Format 8: `LWPI #imm` — WP ← 即値",
  LIMI: "Format 8: `LIMI #imm` — 割り込みマスク ← 即値",
  STWP: "Format 8: `STWP Rn` — Rn ← WP",
  STST: "Format 8: `STST Rn` — Rn ← ST",
  LST: "Format 8: `LST Rn` — ST ← Rn（TMS9995+）",
  LWP: "Format 8: `LWP Rn` — WP ← Rn（TMS9995+）",
  IDLE: "Format 7: 割り込み待ち",
  RSET: "Format 7: リセット相当（マスクも落とす）",
  CKON: "Format 7: Clock on（990 系外部）",
  CKOF: "Format 7: Clock off",
  LREX: "Format 7: Load and restart",
  RT: "別名: `B (R11)` — BL からの復帰",
  NOP: "別名: `JMP` 相対 0（次命令へ）",
};
