.PHONY: all build run test check clean release

all: build

build:
	cargo build

run:
	cargo run --bin retrocpu_emu

test:
	cargo test

check:
	cargo check

release:
	cargo build --release

clean:
	cargo clean
