import type { CallingConvention, CpuArchitecture } from "../types";

/** asm-rules.mdc の呼び出し規約（MN1610 / MN1613 共通） */
export const MN1613_CALLING_CONVENTION: CallingConvention = {
  argRegisters: ["R0", "R1"],
  returnRegister: "R0",
  calleeSavedNote:
    "サブルーチン内で R4〜R7 を書き換える場合は、入口で退避し出口で復元する。",
  summaryMarkdown: [
    "**呼び出し規約**",
    "",
    "| 役割 | レジスタ / 場所 |",
    "|------|----------------|",
    "| 第1引数 | `R0` |",
    "| 第2引数 | `R1` |",
    "| 第3引数以降 | スタック |",
    "| 戻り値 | `R0` |",
    "",
    "サブルーチン内で **R4〜R7** を書き換える場合は、必ず最初と最後でスタックへ退避・復元する。",
  ].join("\n"),
};

/** MN1610 命令 */
const MN1610_MNEMONICS = [
  "L",
  "ST",
  "B",
  "BAL",
  "IMS",
  "DMS",
  "A",
  "S",
  "C",
  "CB",
  "MV",
  "MVB",
  "BSWP",
  "DSWP",
  "LAD",
  "AND",
  "OR",
  "EOR",
  "SR",
  "SL",
  "SBIT",
  "RBIT",
  "TBIT",
  "AI",
  "SI",
  "LPSW",
  "H",
  "PUSH",
  "POP",
  "RET",
  "RD",
  "WT",
  "MVI",
] as const;

/** MN1613 追加命令 */
const MN1613_EXTRA_MNEMONICS = [
  "LD",
  "STD",
  "LR",
  "STR",
  "MVWR",
  "MVWI",
  "MVBR",
  "BSWR",
  "DSWR",
  "PSHM",
  "POPM",
  "AWR",
  "AWI",
  "SWR",
  "SWI",
  "CWR",
  "CWI",
  "CBR",
  "CBI",
  "NEG",
  "AD",
  "SD",
  "M",
  "D",
  "DAA",
  "DAS",
  "LADR",
  "LADI",
  "ANDR",
  "ANDI",
  "ORR",
  "ORI",
  "EORR",
  "EORI",
  "FA",
  "FS",
  "FM",
  "FD",
  "FIX",
  "FLT",
  "BD",
  "BL",
  "BR",
  "BALD",
  "BALL",
  "BALR",
  "RETL",
  "TSET",
  "TRST",
  "SRBT",
  "DEBP",
  "BLK",
  "RDR",
  "WTR",
  "LB",
  "LS",
  "STB",
  "STS",
  "CPYB",
  "CPYS",
  "CPYH",
  "SETB",
  "SETS",
  "SETH",
] as const;

/** sdas / retrocpu_asm 系ディレクティブ（大文字） */
const ASM_DIRECTIVES = [
  ".ORG",
  "ORG",
  ".EQU",
  "EQU",
  ".WORD",
  "WORD",
  "DW",
  ".DW",
  ".DS",
  "DS",
  ".BLKW",
  "BLKW",
  ".BLKB",
  "BLKB",
  ".AREA",
  "AREA",
  ".GLOBL",
  ".GLOBAL",
  "GLOBL",
  "GLOBAL",
  ".INCLUDE",
  "INCLUDE",
  ".MACRO",
  "MACRO",
  ".ENDM",
  "ENDM",
  ".REPT",
  "REPT",
  ".IRP",
  "IRP",
  ".IRPC",
  "IRPC",
  ".MEXIT",
  "MEXIT",
  ".END",
  "END",
] as const;

const MN1610_REGISTERS = [
  "R0",
  "R1",
  "R2",
  "R3",
  "R4",
  "SP",
  "STR",
  "X0",
  "X1",
] as const;

const MN1613_REGISTERS = [
  ...MN1610_REGISTERS,
  "CSBR",
  "SSBR",
  "TSR0",
  "TSR1",
  "OSR0",
  "OSR1",
  "OSR2",
  "OSR3",
  "SBRB",
  "ICB",
  "NPP",
  "TCR",
  "TIR",
  "TSR",
  "SCR",
  "SSR",
  "SOR",
  "IISR",
  "DR0",
] as const;

/** 共有拡張子（ステータスバー選択の既定 CPU を使う） */
export const SHARED_ASM_EXTENSIONS = ["asm", "s", "inc", "h"] as const;

/** MN1610 アーキテクチャ定義 */
export const mn1610Architecture: CpuArchitecture = {
  id: "mn1610",
  displayName: "MN1610",
  extensions: ["asm", "s", "mn1610", "inc", "h"],
  languageId: "mn1613asm",
  mnemonics: new Set(MN1610_MNEMONICS),
  directives: new Set(ASM_DIRECTIVES),
  registers: new Set(MN1610_REGISTERS),
  callMnemonics: new Set(["BAL"]),
  labelRefMnemonics: new Set(["B", "BAL", "L", "ST", "IMS", "DMS"]),
  callingConvention: MN1613_CALLING_CONVENTION,
};

/** MN1613 アーキテクチャ定義（MN1610 上位互換） */
export const mn1613Architecture: CpuArchitecture = {
  id: "mn1613",
  displayName: "MN1613",
  extensions: ["asm", "s", "mn1613", "mn1610", "inc", "h"],
  languageId: "mn1613asm",
  mnemonics: new Set([...MN1610_MNEMONICS, ...MN1613_EXTRA_MNEMONICS]),
  directives: new Set(ASM_DIRECTIVES),
  registers: new Set(MN1613_REGISTERS),
  callMnemonics: new Set(["BAL", "BL", "BALD", "BALL", "BALR"]),
  labelRefMnemonics: new Set([
    "B",
    "BAL",
    "BD",
    "BL",
    "BALD",
    "BALL",
    "L",
    "ST",
    "LD",
    "STD",
    "IMS",
    "DMS",
  ]),
  callingConvention: MN1613_CALLING_CONVENTION,
};
